import { z } from "zod";

export const filePointerSchema = z.object({
  _type: z.literal("file"),
  object: z.string(),
  filesize: z.number(),
  mimeType: z.string(),
});

const audioPartSchema = z.object({
  duration: z.number(),
  variants: z.object({
    hq: filePointerSchema,
    lq: filePointerSchema,
  }),
});

// ---------------------------------------------------------------------------
// Wire format (EAB): a lesson as it appears in jnm-meta.json, generated by
// gen-jnm-meta.mjs. Each Jen Nia Mondo lesson has two named recordings —
// the teaching track ("lesson") and the standalone dialogue for repeated
// listening — plus an optional pointer to its structured written content
// (transcript, vocabulary, notes, exercises).
// ---------------------------------------------------------------------------

const lessonWireSchema = z.object({
  id: z.string(),
  number: z.number(),
  part: z.number(), // published volume: 1 or 2
  title: z.string(),
  audio: z.object({
    lesson: audioPartSchema.nullable(),
    dialogue: audioPartSchema.nullable(),
  }),
  content: filePointerSchema.nullable(),
  illustrations: z.array(filePointerSchema).default([]),
});

// ---------------------------------------------------------------------------
// Internal shape: what the rest of the app sees. The teaching track's
// duration/variants are hoisted to the top level, so every existing
// consumer (player, download manager, lesson list, progress) keeps
// working without knowing the wire format changed. The dialogue
// recording, content pointer, lesson number and volume ride along as
// additional fields for newer UI to pick up incrementally.
// A lesson with no teaching recording is unplayable and is dropped here
// (the manifest generator refuses to publish one anyway).
// ---------------------------------------------------------------------------

export const courseMetaSchema = z
  .object({
    schemaVersion: z.literal(1),
    course: z.string(),
    generatedAt: z.string().optional(),
    lessons: z.array(lessonWireSchema),
  })
  .transform((meta) => ({
    buildVersion: meta.schemaVersion,
    lessons: meta.lessons.flatMap((l) =>
      l.audio.lesson === null
        ? []
        : [
            {
              id: l.id,
              title: l.title,
              duration: l.audio.lesson.duration,
              variants: l.audio.lesson.variants,
              number: l.number,
              part: l.part,
              dialogue: l.audio.dialogue,
              content: l.content,
              illustrations: l.illustrations,
            },
          ]
    ),
  }));

export const courseIndexEntrySchema = z.object({
  // this id is NOT CourseNameSchema -- we don't want to reject if the remote
  //   has added courses our app version hasn't heard of
  id: z.string(),
  meta: filePointerSchema,
  lessons: z.number(),
});

export const allCoursesSchema = z.object({
  buildVersion: z.literal(2),
  casBaseURL: z.string(),
  courses: z.array(courseIndexEntrySchema),
});

export const storedAllCoursesSchema = z.object({
  timestamp: z.number(),
  data: allCoursesSchema,
});

export type FilePointer = z.infer<typeof filePointerSchema>;
export type ObjectPointer = Pick<FilePointer, "object">;
export type AudioPart = z.infer<typeof audioPartSchema>;
export type CourseMetadata = z.infer<typeof courseMetaSchema>;
export type LessonData = CourseMetadata["lessons"][number];
export type LessonVariants = LessonData["variants"];
export type CourseIndexEntry = z.infer<typeof courseIndexEntrySchema>;
export type CourseIndex = z.infer<typeof allCoursesSchema>;
export type StoredCourseIndex = z.infer<typeof storedAllCoursesSchema>;
